apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: likhitha-rolebinding
 namespace: team3-ns
subjects:
- kind: User
  name: raj
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: likhitha-sa
  namespace: team3-ns
roleRef:
 kind: Role
 name: likhitha-role
 apiGroup: rbac.authorization.k8s.io